### ISSUE TITLE
The current Date & Time needs to be set every time the device is started

### ISSUE THREAD

**Issue by Sathish-Chandrasekaran-Pinayour** [Sathish-Chandrasekaran-Pinayour/Eximius_Android_Training_Batch1#1]
**Issue :**
The latest Date & Time needs to be set every time the device is started. The previously set "latest value" doesn't get retained when we restart the device.

**Steps to Reproduce :**
1. Flash the Android Nougat image for RPI 3.
2. Check the Date & Time value when the device comes up.
3. Set the latest value for Date & Time under "Settings".
4. Restart the device and check the Date & Time once the device comes up.

**Expected Result :**
The current Date & Time should get reflected once set.

**Actual Result :**
The current Date & Time doesn't get reflected when the device is restarted. The Date is shown as "Jan 1, 1970" (every single time, we restart the device) and Time is a random value.

**User Impact:**
High, since we have to set the current Date & Time everytime we restart the device. Note that, we can connect to WiFi only when we set the current Date & Time.

**Comment by Sathish-Chandrasekaran-Pinayour** [comment]
@anutriEximius : Please check the following :
1. Why is the Date & Time value not retained when we restart the device?
2. Is the device lacking a RTC? If yes, could this issue be worked around?

**Comment by anutriEximius** [comment]
@Sathish-Chandrasekaran-Pinayour: Below is my research overview to update Date & Time.

The Raspberry Pi is designed to be an ultra-low cost computer, one thing it does not come with is a real-time clock. This means that every time you switch off your Raspberry Pi it forgets what the time is and you have to manually set it again next time you switch your Raspberry Pi on.

There are two options by which you can sync your raspberry pi time.

Solution 1: you can use RTC or any hardware clock and you can sync your rpi time with the clock.

Solution 2: You can use NTP server to sync your raspberry pi time. At this case you need your rpi connected to internet.

Here is the link to set up NTP for RPI time auto update
http://raspberrypi.tomasgreno.cz/ntp-client-and-server.html

You can also interface RTC to I2C of RPI, here are the few steps  
https://learn.adafruit.com/adding-a-real-time-clock-to-raspberry-pi/set-rtc-time

**Comment by Sathish-Chandrasekaran-Pinayour** [comment]
@anutriEximius - Thanks for the detailed explanation. I will close this issue as "Won't Fix" since this is not a software bug. 

Please check with the Hardware team and check how we can interface RTC to RPI 3 if we procure the hardware in future.
