### ISSUE TITLE
Audio is not getting routed to wireless BT speaker even after successful pairing.

### ISSUE THREAD

**Issue by Sathish-Chandrasekaran-Pinayour** [Sathish-Chandrasekaran-Pinayour/Eximius_Android_Training_Batch1#5]
**Issue :**
Audio is not getting routed to wireless BT speaker, paired & connected to RPI 3. Instead, it continues to be heard on the HDMI TV Speakers.

**Steps to Reproduce :**
1. Flash the Android Nougat image for RPI 3.
2. Pair & Connect RPI 3 with a wireless BT Speaker.
3. Play local/streaming media using any of the following ways :
    1. Settings --> Sound --> Toggle the volume panel of Media/Alarm/Notification streams.
    2. Push a media (any supported audio/video format) to sdcard and play it using native/3rd party apps.
    3. Play a streaming media (Saavn/YouTube etc.) via a web browser.

**Expected Result :**
Audio should get routed to the wireless BT speaker once it is paired & connected.

**Actual Result :**
Audio doesn't get routed to the wireless BT speaker. Instead, the audio continues to be heard on the HDMI TV Speakers.

**User Impact :**
High, since this is a poilcy breach.

**Logcat :**
[Wireless_BT_Connect.txt](https://github.com/Sathish-Chandrasekaran-Pinayour/Eximius_Android_Training_Batch1/files/1720524/Wireless_BT_Connect.txt)

**Comment by girishbeximiusdesign** [comment]
From the attached logs, i can see the sequence pertaining to :
1. BT Speaker connection
2. A2DP State Machine update
3. MediaRouter updating the route table for the BT device.

However, amidst 2 and 3, i also see the following snippet which has led to this issue :
02-02 17:19:44.610 D/APM_AudioPolicyManager(  136): setDeviceConnectionState() could not find HW module for device 00000080

Root-Cause :
The A2DP HAL Libary (audio.a2dp.default.so) is not getting loaded. The AudioFlinger will take the help of AudioPolicyManager to load the correct HAL after which it will start rendering the pcm samples to the HW.

Fix :
The Bluedroid A2DP HAL support is already present in the RPI 3 workspace. However, the rpi3.mk file needs to be updated to get the audio.a2dp.default.so generated which will fix this issue.

Will create a pull request after testing the changes thoroughly.

**Comment by girishbeximiusdesign** [comment]
@Sathish-Chandrasekaran-Pinayour : Please review the pull request : https://github.com/Sathish-Chandrasekaran-Pinayour/Eximius_Android_Training_Batch1/pull/11.

After making the changes, i observed that the A2DP HAL Library : audio.a2dp.default.so is getting loaded successfully. It is present in /out/rpi3/system/lib/hw. Audio is heard out of the BT speaker.

**Comment by Sathish-Chandrasekaran-Pinayour** [comment]
@girishbeximiusdesign : Have merged your pull request : https://github.com/Sathish-Chandrasekaran-Pinayour/Eximius_Android_Training_Batch1/pull/11 . The changes are in mainline now.

Closing this ticket.
